### ISSUE TITLE
Panic on dollar vars

### ISSUE THREAD

**Issue by odino** [abs-lang/abs#78]
```
⧐  $1
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/abs-lang/abs/lexer.(*Lexer).readCommand(0xc0000f0060, 0xc000070cc8, 0x10)
	/go/src/github.com/abs-lang/abs/lexer/lexer.go:286 +0xdd
github.com/abs-lang/abs/lexer.(*Lexer).NextToken(0xc0000f0060, 0x10, 0x53de80, 0x553801, 0xc000070a80)
	/go/src/github.com/abs-lang/abs/lexer/lexer.go:127 +0x473
github.com/abs-lang/abs/parser.(*Parser).nextToken(0xc000166000)
	/go/src/github.com/abs-lang/abs/parser/parser.go:122 +0x5b
github.com/abs-lang/abs/parser.New(0xc0000f0060, 0xc0000f0060)
	/go/src/github.com/abs-lang/abs/parser/parser.go:114 +0x140a
github.com/abs-lang/abs/repl.Run(0xc00014e004, 0x2, 0x1)
	/go/src/github.com/abs-lang/abs/repl/repl.go:100 +0x8e
github.com/abs-lang/abs/repl.executor(0xc00014e004, 0x2)
	/go/src/github.com/abs-lang/abs/repl/repl.go:91 +0x76
github.com/c-bata/go-prompt.(*Prompt).Run(0xc0000c8000)
	/go/src/github.com/c-bata/go-prompt/prompt.go:73 +0x764
github.com/abs-lang/abs/repl.Start(0x581860, 0xc00000e010, 0x581880, 0xc00000e018)
	/go/src/github.com/abs-lang/abs/repl/repl.go:61 +0xec
main.main()
	/go/src/github.com/abs-lang/abs/main.go:26 +0x11f
exit status 2
Makefile:12: recipe for target 'repl' failed
make: *** [repl] Error 1
```

**Comment by odino** [comment]
```
⧐  $11111111111111111111111111
bash: 111111111111111111111111: command not found

⧐  $echo 2
bash: cho: command not found

⧐  $eecho 2

⧐  $eecho 2)
2
⧐  
```

Lol I see what's happening here... :)
